name: Test Flask API Artefacts

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: List directory contents for debugging
      run: ls -R

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Remplacez par la version de Python souhaitée

    - name: Install dependencies
      run: |
        cd Flask_API_artefacts
        pip install -r requirements.txt
        pip install pytest

    - name: Run Flask application
      run: |
        python app.py
      working-directory: Flask_API_artefacts

    
