name: Test and Deploy Flask API

on: [push]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Remplacez par la version de Python que vous utilisez, par exemple '3.8'

    - name: Install dependencies
      run: |
        cd Flask_API_artefacts
        pip install -r requirements.txt

    - name: Run Flask application
      run: |
        export FLASK_APP=app.py
        flask run --host=0.0.0.0 --port=5000 &
      working-directory: Flask_API_artefacts

   